### ISSUE TITLE
Could not create. python manage.py dumps create

### ISSUE THREAD

**Issue by vlikin** [cuducos/alchemydumps#10]
```
Traceback (most recent call last):
  File "/home/viktor/Software/pycharm-community-4.5.2/helpers/pydev/pydevd.py", line 2357, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/viktor/Software/pycharm-community-4.5.2/helpers/pydev/pydevd.py", line 1777, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/github/vlikin/car_budget/flask/manage.py", line 11, in <module>
    script_manager.run()
  File "/github/vlikin/car_budget/flask/.env/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/github/vlikin/car_budget/flask/.env/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/github/vlikin/car_budget/flask/.env/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/github/vlikin/car_budget/flask/.env/local/lib/python2.7/site-packages/flask_alchemydumps/__init__.py", line 48, in create
    data = alchemy.get_data()
  File "/github/vlikin/car_budget/flask/.env/local/lib/python2.7/site-packages/flask_alchemydumps/helpers/database.py", line 38, in get_data
    data[model.__name__] = dumps(query.all())
  File "/github/vlikin/car_budget/flask/.env/local/lib/python2.7/site-packages/sqlalchemy/ext/serializer.py", line 152, in dumps
    pickler.dump(obj)
  File "/github/vlikin/car_budget/flask/.env/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: <flask_script.commands.Command object at 0x7fcbaad5c750>: can't pickle function objects
```

**Comment by cuducos** [comment]
The error happens when AlchemyDumps is trying to get the models from your application.

Can you share your models so we can debug this, please?

If there's nothing new (or wrong) with your models, maybe we need a filter in the [add_subclasses() helper](https://github.com/cuducos/alchemydumps/blob/master/flask_alchemydumps/helpers/database.py#L23) to be sure that everything passed to [get_data() helper](https://github.com/cuducos/alchemydumps/blob/master/flask_alchemydumps/helpers/database.py#L31) is an object valid for pickling. But without your models I can't reproduce this error here to investigate it.

**Comment by vlikin** [comment]
This my project. https://github.com/vlikin/car_budget/tree/master/flask
if you have a time we could have a Hangout meeting.

Yes. I have Table object. These define  data structure. There are models these are inherited from tables. These contains the entity logic. So Alchemy could count them twice.

**Comment by cuducos** [comment]
Ok, let me play around with your code a bit, then we talk. Can you point me to the exact file where you define your mapped classes (models)?

Regarding the Hangouts, sounds a good idea, maybe some pair programming to sort this out. Where are you in terms of timezone? I'm in BST (British Summer Time).

**Comment by vlikin** [comment]
Hello. I am from Ukraine, Chrnigov. GMT+3. My email is viktor.likin@gmail.com. To create the database structure run "python manage.py db_rebuild" Than  "python manage.py dumps create". I receive errors described above.

**Comment by vlikin** [comment]
Do not use the migration script.

**Comment by cuducos** [comment]
Sorry, but I have to try it for the third time:

 * Where is the file where you define your models?

That's the crucial point here.

**Comment by vlikin** [comment]
ext.user.table, ext.user.model, ext.budget.table, ext.budget.model. The models inherit the table Objects.

**Comment by vlikin** [comment]
https://github.com/vlikin/car_budget/tree/master/flask/ext/budget/model
https://github.com/vlikin/car_budget/tree/master/flask/ext/budget/table
https://github.com/vlikin/car_budget/tree/master/flask/ext/user/table
https://github.com/vlikin/car_budget/tree/master/flask/ext/user/model

**Comment by cuducos** [comment]
Ok, now I see! Thanks for the links, they saved a lot of time.

It looks like the issue is with `InstanceModel`: as it requires an argument in its `__init__` method, it messes up with `__reduce__` and `__reduce_ex__` class methods used for pickling (dumping).

I still studying how to fix it, and this is a completely new field of study for me. So I'm just dropping it here in case anybody can jump in and help.

Some useful references:

* [Can't pickle int object error when object comes from SQLAlchemy?](http://stackoverflow.com/questions/7844276/cant-pickle-int-object-error-when-object-comes-from-sqlalchemy)
* [Pickling and unpickling extension types](https://docs.python.org/2/library/pickle.html#pickling-and-unpickling-extension-types)

**Comment by vlikin** [comment]
Thank you. I try also to resolve it.

**Comment by cuducos** [comment]
Ok, **wrong guess**, sorry. I just implemented tests for the situation I descried earlier and they pass. If you wanna play around, check the [fix-issue-10](https://github.com/cuducos/alchemydumps/tree/fix-issue-10) branch (take a look on the latest commit to see the changes).

My **new guess** comes from this [StackOverflow answer](http://stackoverflow.com/questions/4677012/python-cant-pickle-type-x-attribute-lookup-failed):

    Nesting classes makes pickle fail, since it relies on the path of the object inside your application to reconstruct it later.

AlchemyDumps uses pickle to dump do the backup. If nested classes mess with pickle, and you models are declared that way, probably that's not gonna work. Does it seem to fit you case?

And, finally, any ideas on how to overcome this pickle limitation?

Try to fix and keep sharing your findings here. It's easier to do it sharing and debating :)

**Comment by vlikin** [comment]
from sqlalchemy.ext.serializer import loads, dumps
from ext.user.table.user import UserTable as User
users = User.query.all()
s = dumps(users[0])
SqlAlchemy fails the same way. SqlA "dumps" uses pickle. Pickle is very dangerous for the reason. It dumps everything. We need sanitation. It is the very good idea when we want to separate it to chunks. Now I need store/recover the databases. Why do we not use simple SQL dumps?

**Comment by cuducos** [comment]
The code you used only fails if the tables is empty (I'm opening another Issue for this):

```
In [1]: from sqlalchemy.ext.serializer import loads, dumps
In [2]: from ext.user.table.user import UserTable as User
In [3]: users = User.query.all()
In [4]: s = dumps(users[0])
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-9cf913d7f7a1> in <module>()
----> 1 s = dumps(users[0])
IndexError: list index out of range
In [5]: db = app.extensions['alchemydumps'].db
In [6]: db.session.add(User(email='a@a'))
In [7]: db.session.commit()
In [8]: users = User.query.all()
In [9]: s = dumps(users[0])
In [10]:
```

Regarding the use of `dumps()`: no special reason.

Feel free to start a branch, or send a PR changing the method for something else :)

**Comment by cuducos** [comment]
@vlikin I was thinking and I believe there are three good reasons to keep working with SQLAlchemy `dumps()` method:

1. AlchemyDumps is supposed to work alongside SQLAlchemy, and following their methods is a good way to keep this compatibility as close as possible.
2. Simple SQL can be problematic, because writing SQL code is exactly the problem SQLAlchemy try to avoid; in other words, PostgreSQL SQL code may be incompatible with MySQL, or with SQLite and so on — and to sort this issues we add an ORM.
3. Due to 1 and 2, I believe there's no secure way to generate safe SQL code from SQLAlchemy.

Anyway, that said, any PR is welcomed. I just believe if you try to write something different from `dumps()` the best choice would be to add it as an option, and not as replacement to the SQLAlchemy `dumps()`.
