### ISSUE TITLE
Can you add support for Flask 2.x?

### ISSUE THREAD

**Issue by mmozos** [cuducos/alchemydumps#26]
Kind regards and many thanks in advance.

**Comment by cuducos** [comment]
I am not following Flask anymore. So I don't when I can explore this update.

Just saying that so:
- anyone fell free to share what exactly breaks in Flask 2, this helps me estimate the stint for this update
- anyone knows that PRs are welcomed : )

**Comment by mmozos** [comment]
#27 [Here it is a good explanation](https://devclass.com/2021/05/13/flask-2-0-pours-out-updates-to-web-application-framework/) about changes, looks like it safe to merge

**Comment by cuducos** [comment]
> Here it is a good explanation about changes

This might be a good explanation about changes in Flask 2, but it does not give a clue about _what exactly breaks in Flask 2_ when using the current release. Can you be specific? Any API changes that the project needs? Any method we use is deprecated? Any error message?

> looks like it is safe to merge

I don't think so, since there are no tests using Flask 2. Gonna pull this thread there.
